version: '3.4'

services:
  authentication.service:
    #image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: ./src/Authentication.Service
      dockerfile: Dockerfile
    depends_on:
      - auth.database

  auth.database:
    build:
      context: ./src/Authentication.Service/Config/AuthDatabase.Docker
      dockerfile: Dockerfile.AuthDb
    container_name: auth.database
    #image: ${DOCKER_REGISTRY-}auth.database
    volumes:
      - auth-data:/var/lib/db
    ports:
      - "1434:1433"

volumes:
  auth-data:
    name: auth-data
